esphome:
  name: blebridge
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blebridge Fallback Hotspot"
    password: !secret portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80

esp32_ble_tracker:

sensor:
  - platform: atc_mithermometer
    mac_address: !secret office_sensor_mac
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    battery_level:
      name: "Office Battery-Level"
    battery_voltage:
      name: "Office Battery-Voltage"
  - platform: atc_mithermometer
    mac_address: !secret bathroom_sensor_mac
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    battery_level:
      name: "Bathroom Battery-Level"
    battery_voltage:
      name: "Bathroom Battery-Voltage"
  - platform: atc_mithermometer
    mac_address: !secret familyroom_sensor_mac
    temperature:
      name: "Family Room Temperature"
    humidity:
      name: "Family Room Humidity"
    battery_level:
      name: "Family Room Battery-Level"
    battery_voltage:
      name: "Family Room Battery-Voltage"